services:
  - type: web
    name: goalapp-frontend-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://goalapp-backend-j2cx.onrender.com/api/v1
      - key: VITE_USE_MOCKS
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
